version: '3'
services:
  nginx_ws:
      container_name: s2r_web_app
      image: s2r_ui
      build:
        context: ./frontend/angularUI
        dockerfile: Dockerfile
      network_mode: bridge
      restart: always
      volumes:
        - ./logs/nginx:/var/log/nginx
      ports:
        - "80:80"
      command: ["nginx", "-g", "daemon off;"]

  s2r_api:
    container_name: s2r_mapping_tool
    image: s2r_img
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    restart: always
    volumes:
    - ./input:/smart/input
    - ./output:/smart/output
    - ./uploads:/smart/uploads
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8081"]
    depends_on:
      - nginx_ws
