version: '3'
services:
  smart_ws:
      container_name: smart_ws
      image: smart_ws_img
      hostname: smart_ws
      build:
        context: ./frontend/angularUI
        dockerfile: Dockerfile
      network_mode: bridge
      restart: unless-stopped
      volumes:
        - ./logs/nginx:/var/log/nginx
      ports:
        - "${NGINX_PORT}:80"
      command: ["nginx", "-g", "daemon off;"]

  smart_api:
    container_name: smart_api
    image: smart_api_img
    hostname: smart_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
    - ./input:/smart/input
    - ./output:/smart/output
    - ./uploads:/smart/uploads
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8081"]
    depends_on:
      - nginx_ws
