version: '3'
services:
  nginx_ws:
      container_name: smart_app
      image: smart_app_img
      hostname: smart_app
      build:
        context: ./frontend/angularUI
        dockerfile: Dockerfile
      restart: unless-stopped
      volumes:
        - ./logs/nginx:/var/log/nginx
      ports:
        - "${NGINX_PORT}:80"
      command: ["nginx", "-g", "daemon off;"]
      depends_on:
        - smart_api

  smart_api:
    container_name: smart_api
    image: smart_api_img
    hostname: smart_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
    - ./input:/smart/input
    - ./output:/smart/output
    - ./uploads:/smart/uploads
